### ISSUE TITLE
Trying to get AWS deployment working

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/jumpbox-deployment#3]
@cppforlife I took the aws/cpi.yml which looked to have been copied across from bosh-deployment I think, and started trying to update it to deploy jumpbox-deployment, but its failing with a `registry.username` property missing. But I can't see where this is coming from. Ideas?

```
git clone https://github.com/drnic/jumpbox-deployment -b aws-support
cd jumpbox-deployment

bosh2 create-env jumpbox.yml -o aws/cpi.yml --vars-store tmp/aws-creds.yml -l tmp/aws-starkandwayne-demo.yml --state tmp/aws-demo.json
Deployment manifest: '/Users/drnic/Projects/bosh_deployments/jumpbox-deployment/jumpbox.yml'
Deployment state: 'tmp/aws-demo.json'

Started validating
  Downloading release 'os-conf'... Skipped [Found in local cache] (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Downloading release 'bosh-aws-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-aws-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:00)

Started installing CPI
  Compiling package 'ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042'... Finished (00:00:00)
  Compiling package 'bosh_aws_cpi/c2563067cbc20e3406ea36ca2984df2f0eaebcb0'... Finished (00:00:00)
  Installing packages... Finished (00:00:01)
  Rendering job templates... Failed (00:00:00)
Failed installing CPI (00:00:02)

Installing CPI:
  Rendering and uploading Jobs:
    Rendering job templates for installation:
      Rendering templates for job 'aws_cpi/2a34fab07ff9a36e43ede22e227c02918a5ccdef':
        Rendering template src: cpi.json.erb, dst: config/cpi.json:
          Rendering template src: /Users/drnic/.bosh/installations/9a34696d-a17d-4c88-58ad-a37f47226d61/tmp/bosh-release-job664264008/templates/cpi.json.erb, dst: /Users/drnic/.bosh/installations/9a34696d-a17d-4c88-58ad-a37f47226d61/tmp/rendered-jobs295073020/config/cpi.json:
            Running ruby to render templates:
              Running command: 'ruby /Users/drnic/.bosh/installations/9a34696d-a17d-4c88-58ad-a37f47226d61/tmp/erb-renderer818803598/erb-render.rb /Users/drnic/.bosh/installations/9a34696d-a17d-4c88-58ad-a37f47226d61/tmp/erb-renderer818803598/erb-context.json /Users/drnic/.bosh/installations/9a34696d-a17d-4c88-58ad-a37f47226d61/tmp/bosh-release-job664264008/templates/cpi.json.erb /Users/drnic/.bosh/installations/9a34696d-a17d-4c88-58ad-a37f47226d61/tmp/rendered-jobs295073020/config/cpi.json', stdout: '', stderr: '/Users/drnic/.bosh/installations/9a34696d-a17d-4c88-58ad-a37f47226d61/tmp/erb-renderer818803598/erb-render.rb:189:in `rescue in render': Error filling in template '/Users/drnic/.bosh/installations/9a34696d-a17d-4c88-58ad-a37f47226d61/tmp/bosh-release-job664264008/templates/cpi.json.erb' for aws_cpi/0 (line 17: #<TemplateEvaluationContext::UnknownProperty: Can't find property 'registry.username'>) (RuntimeError)
	from /Users/drnic/.bosh/installations/9a34696d-a17d-4c88-58ad-a37f47226d61/tmp/erb-renderer818803598/erb-render.rb:175:in `render'
	from /Users/drnic/.bosh/installations/9a34696d-a17d-4c88-58ad-a37f47226d61/tmp/erb-renderer818803598/erb-render.rb:200:in `<main>'
':
                exit status 1

Exit code 1
```

Protips? Did I hack at aws/cpi.yml too much?

**Comment by cppforlife** [comment]
@drnic you've killed ssh tunnel which is required for aws: https://github.com/drnic/jumpbox-deployment/commit/910a660cfa91b9b6d40e1f0df527a0eb11dd8fc1#diff-bc285dbc3ed690339a31d15ec626a9abL34
